#!/bin/bash
set -e

node_modules/.bin/elm-live src/Main.elm --ide=vscode --dir=docs --start-page="index.html" --port=8001 -- --output="docs/js/main.js" --debug

# node_modules/.bin/elm-live src/Main.elm --open
